// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgstriffcggguosphcmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhnc3RyaWZmY2dnZ3Vvc3BoY214Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMDkzNTUsImV4cCI6MjA2NTc4NTM1NX0.jYQc9TPnG0gfl1pfZ-OoqIQIDL4eTsL-K4X6KTiJe30";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);